### ISSUE TITLE
oneuiweb.dev doesn't exists anymore

### ISSUE THREAD

**Issue by cescur** [diekus/OneUI-CSS#59]
Is there a new URL to look docs or something?

**Comment by youngsoo1-Kim** [comment]
Dear @cescur 
First of all, Thank you for your interest in our oneuiweb project.
oneuiweb.dev site is currently under maintenance.
We will open asap
Thank you!

**Comment by ProCode-Software** [comment]
It still does not work.

**Comment by youngsoo1-Kim** [comment]
Dear @cescur and @ProCode-Software 
Hi
Our https://oneuiweb.dev/ has been reactivated a while ago (This site is currently activating sequentially, and it will take up to an hour.)
Please visit again 
Thank you!
